name: Move Merged YAML Files

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed

jobs:
  process-merged-yaml:
    if: github.event.pull_request.merged == true # Only proceed if the PR was merged
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch the modified files in the pull request
      - name: Fetch modified YAML files
        id: fetch_files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the list of modified files
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" > api_response.json

          # Debug: Print the API response for visibility
          echo "API Response:"
          cat api_response.json

          # Extract YAML files in /new_cluster_requests
          jq -r '.[] | select(.filename | startswith("new_cluster_requests/") and endswith(".yaml")) | .filename' api_response.json > changed_files.txt

          # Exit if no matching files were found
          if [ ! -s changed_files.txt ]; then
            echo "No matching YAML files found in /new_cluster_requests."
            exit 0
          fi

          # Debug: Print matched files
          echo "Matched files:"
          cat changed_files.txt

      # Step 3: Move the YAML files to approved_cluster_requests
      - name: Move files
        if: always() # Only runs if Step 2 succeeds
        run: |
          while read -r file; do
            mv "$file" ./approved_cluster_requests/
            git add ./approved_cluster_requests/
            git rm "$file"
          done < changed_files.txt

      # Step 4: Commit and push changes to the repository
      - name: Commit and push changes
        if: always() # Only runs if Step 2 succeeds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Move merged YAML file(s) to approved_cluster_requests"
          git push

