name: Process Merged YAML File

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed

jobs:
  process-merged-file:
    if: github.event.pull_request.merged == true # Only proceed if the PR was merged
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch the list of modified files in the PR
      - name: Fetch modified files
        id: fetch_files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            | jq -r '.[] | select(.filename | startswith("new_cluster_requests/") and .filename | endswith(".yaml")) | .filename' > changed_files.txt

          if [ ! -s changed_files.txt ]; then
            echo "No matching YAML files found in /new_cluster_requests."
            exit 0
          fi

          echo "Matched files:"
          cat changed_files.txt

      # Move the YAML files
      - name: Move files
        run: |
          while read -r file; do
            mv "$file" ./approved_cluster_requests/
            git add ./approved_cluster_requests/
            git rm "$file"
          done < changed_files.txt

      # Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Move merged YAML file(s) to approved_cluster_requests"
          git push

